// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcnL3rz1i7Fd9TymaYcAaOL1F3ftitkHY',
    appId: '1:451418679007:web:fc1a3fc3e172a424efab6a',
    messagingSenderId: '451418679007',
    projectId: 'schoolbusnotification-61158',
    authDomain: 'schoolbusnotification-61158.firebaseapp.com',
    storageBucket: 'schoolbusnotification-61158.appspot.com',
    measurementId: 'G-DMWPJ76C4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV35_jRaDd3dy4zhE1s1kVyzoQ_RlSDrc',
    appId: '1:451418679007:android:1c59edff7fe4d947efab6a',
    messagingSenderId: '451418679007',
    projectId: 'schoolbusnotification-61158',
    storageBucket: 'schoolbusnotification-61158.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZnvOSufTIKvVx8YdFN96E3o_bQSbefG8',
    appId: '1:451418679007:ios:4f9afe06420959faefab6a',
    messagingSenderId: '451418679007',
    projectId: 'schoolbusnotification-61158',
    storageBucket: 'schoolbusnotification-61158.appspot.com',
    iosBundleId: 'com.example.schoolBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZnvOSufTIKvVx8YdFN96E3o_bQSbefG8',
    appId: '1:451418679007:ios:def1405c4ef60f19efab6a',
    messagingSenderId: '451418679007',
    projectId: 'schoolbusnotification-61158',
    storageBucket: 'schoolbusnotification-61158.appspot.com',
    iosBundleId: 'com.example.schoolBus.RunnerTests',
  );
}
